### PR TITLE
WIP added travis ci

### PR DESCRIPTION
**Pull request by robinlehrmann**
Could you activate travis ci ? I want to test it.

### CODE REVIEW

**Review by Felandil — COMMENTED** [review]
Hey!
Please change 
- mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Tangle.Net\bin\Debug\Tangle.Net.dll
To
- mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Tangle.Net\bin\Release\Tangle.Net.dll

Afterwards I'll merge everything!

**Comment by robinlehrmann** [comment]
Done. Should we add some other scripts to that ? Do you want a tarball zip archive and or want to deploy it to a service ?

**Comment by Felandil** [comment]
I don't think that's needed right now as the lib itself is not usable (or will not be usable) as standalone. If I understood that wrong, send me a PM on discord

**Comment by robinlehrmann** [comment]
@Felandil It's fine for me :) Now we could link travis CI in your README.md to show, that the tests are passed :)

**Pull request merged**
